---
resource_types:
- name: slack-alert
  type: docker-image
  source:
    repository: arbourd/concourse-slack-alert-resource
    tag: latest

resources:
- name: notify
  type: slack-alert
  icon: slack
  source:
    url: ((slack_webhook))
    # channel: ((slack_channel))
- name: repo
  type: git
  icon: github-circle
  source:
    uri: git@github.com:daichi703n/docker-((docker_image_name)).git
    branch: develop
    private_key: ((github_private_key))
# - name: dockerhub
#   type: docker-image
#   source:
#     repository: daichi703n/docker-awscli
#     username: ((docker_username))
#     password: ((docker_password))

jobs:
- name: create-docker-image
  serial: true
  build_logs_to_retain: 30
  plan:
  - in_parallel:
    - get: repo
      trigger: false
  - task: build-docker-image
    timeout: 1h
    params: &params
      AWS_DEFAULT_REGION: ((aws_default_region))
      AWS_ACCESS_KEY_ID: ((aws_access_key_id))
      AWS_SECRET_ACCESS_KEY: ((aws_secret_access_key))
      DOCKER_IMAGE_NAME: ((docker_image_name))
      DOCKER_USERNAME: ((docker_username))
      DOCKER_PASSWORD: ((docker_password))
    # file: repo/ci/tasks/docker-build.yml
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: docker
          tag: dind
      inputs:
      - name: repo
      outputs: 
      - name: repo
      - name: docker-images
      run: 
        path: /bin/sh
        args: 
        - -c
        - | 
          cd repo/ci/tasks
          source ./docker-lib.sh
          start_docker
          ./docker-build.sh
          docker save daichi703n/awscli > ../../../docker-images/awscli.tar
    on_failure:
      put: notify
      params:
        alert_type: failed
  - task: push-develop-image
    timeout: 1h
    params:
      <<: *params
      DOCKER_TAG: develop
    privileged: true
    # file: repo/ci/tasks/docker-push.yml
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: docker
          tag: dind
      inputs:
      - name: repo
      outputs: 
      - name: repo
      - name: docker-images
      run: 
        path: /bin/sh
        args: 
        - -c
        - |
          cd repo/ci/tasks
          source ./docker-lib.sh
          start_docker
          docker load < ../../../docker-images/awscli.tar
          ./docker-push.sh
    on_failure:
      put: notify
      params:
        alert_type: failed
    
- name: test-docker-image
  serial: true
  build_logs_to_retain: 30
  plan:
  - in_parallel:
    - get: repo
      trigger: true
      passed:
      - create-docker-image
  - task: test-docker-image
    timeout: 1h
    params: *params
    privileged: true
    # file: repo/ci/tasks/docker-test.yml
    # image: docker-awscli-image
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: daichi703n/awscli
          tag: develop
      inputs:
      - name: repo
      run: 
        path: /bin/sh
        args: 
        - -c
        - | 
          cd repo/ci/tasks
          echo "alpine-release: $(cat /etc/alpine-release)"
          ./docker-test.sh
    on_failure:
      put: notify
      params:
        alert_type: failed
